USE formd_db;
CREATE TABLE FORMDSUBMISSION (
    ACCESSIONNUMBER VARCHAR(20) NOT NULL PRIMARY KEY,
    FILE_NUM VARCHAR(30),
    FILING_DATE DATE,
    SIC_CODE VARCHAR(4),
    SUBMISSIONTYPE VARCHAR(255) NOT NULL,
    OVER100PERSONSFLAG VARCHAR(5),
    OVER100ISSUERFLAG VARCHAR(5)
);

CREATE TABLE ISSUERS (
    ACCESSIONNUMBER VARCHAR(20) NOT NULL,
    CIK VARCHAR(10) NOT NULL,
    ENTITYNAME VARCHAR(255) NOT NULL,
    IRSNUMBER VARCHAR(20),
    ENTITYSTATEORCOUNTRY VARCHAR(50),
    ENTITYSTATEORCOUNTRYDESC VARCHAR(255),
    YEAROFINCORPORATION VARCHAR(10),
    YEAROFINCORPORATIONTYPE VARCHAR(10),
    PRIMARY KEY (ACCESSIONNUMBER, CIK),
    FOREIGN KEY (ACCESSIONNUMBER) REFERENCES FORMDSUBMISSION(ACCESSIONNUMBER) ON DELETE CASCADE
);

CREATE TABLE OFFERING (
    ACCESSIONNUMBER VARCHAR(20) NOT NULL PRIMARY KEY,
    INDUSTRYGROUPTYPE VARCHAR(255),
    INDUSTRYGROUPTYPEDESC VARCHAR(255),
    SECURITIESTOTALOFFERINGAMOUNT DECIMAL(18,2),
    SECURITIESTOTALREMAINING DECIMAL(18,2),
    INVESTMENTFUNDTYPE VARCHAR(255),
    INVESTMENTFUNDTYPEDESC VARCHAR(255),
    SALESCOMMISSIONFINDERFEEFLAG VARCHAR(5),
    FEDERALEXEMPTION VARCHAR(255),
    SEC_USE_OF_PROCEEDS VARCHAR(255),
    FOREIGN KEY (ACCESSIONNUMBER) REFERENCES FORMDSUBMISSION(ACCESSIONNUMBER) ON DELETE CASCADE
);

CREATE TABLE RECIPIENTS (
    ACCESSIONNUMBER VARCHAR(20) NOT NULL,
    RECIPIENTNAME VARCHAR(255) NOT NULL,
    RECIPIENTCRDNUMBER VARCHAR(50),
    RECIPIENTSTREET1 VARCHAR(255),
    RECIPIENTSTREET2 VARCHAR(255),
    RECIPIENTCITY VARCHAR(255),
    RECIPIENTSTATE VARCHAR(50),
    RECIPIENTZIP VARCHAR(20),
    RECIPIENTCOUNTRY VARCHAR(50),
    RECIPIENTTYPE VARCHAR(255),
    PRIMARY KEY (ACCESSIONNUMBER, RECIPIENTNAME),
    FOREIGN KEY (ACCESSIONNUMBER) REFERENCES FORMDSUBMISSION(ACCESSIONNUMBER) ON DELETE CASCADE
);

CREATE TABLE SALES_COMPENSATION (
    ACCESSIONNUMBER VARCHAR(20) NOT NULL,
    RECIPIENTNAME VARCHAR(255) NOT NULL,
    ASSOCIATED_BD_CRDNUM VARCHAR(50),
    ASSOCIATED_BD_NAME VARCHAR(255),
    ASSOCIATED_BD_SECNUM VARCHAR(50),
    ASSOCIATED_BD_FIRM VARCHAR(255),
    SALES_COMPEN_AMT DECIMAL(18,2),
    FINDERS_FEE_AMT DECIMAL(18,2),
    PRIMARY KEY (ACCESSIONNUMBER, RECIPIENTNAME),
    FOREIGN KEY (ACCESSIONNUMBER, RECIPIENTNAME) REFERENCES RECIPIENTS(ACCESSIONNUMBER, RECIPIENTNAME) ON DELETE CASCADE
);

CREATE TABLE SIGNATURES (
    ACCESSIONNUMBER VARCHAR(20) NOT NULL,
    SIGNATUREDATE DATE,
    NAME VARCHAR(255) NOT NULL,
    TITLE VARCHAR(255),
    PRIMARY KEY (ACCESSIONNUMBER, NAME),
    FOREIGN KEY (ACCESSIONNUMBER) REFERENCES FORMDSUBMISSION(ACCESSIONNUMBER) ON DELETE CASCADE
);
